"""
Conversation Agents module for Tofia Voice Assistant.
Implements PatientAgent and HospitalAgent for handling conversations with patients and hospital staff.
"""
import logging
import openai
import json
import config
import prompts
import re

logger = logging.getLogger(__name__)

class ConversationAgent:
    """Base class for conversation agents."""
    
    def __init__(self, system_prompt):
        """
        Initialize the conversation agent.
        
        Args:
            system_prompt: System message for the GPT model
        """
        self.system_prompt = system_prompt
        self.conversation_history = []
        self.state = {}
        
        # Configure OpenAI API key
        openai.api_key = config.OPENAI_API_KEY
        self.client = openai.OpenAI(api_key=config.OPENAI_API_KEY)
    
    def add_message(self, role, content):
        """
        Add a message to the conversation history.
        
        Args:
            role: The role ("system", "user", "assistant")
            content: The message content
        """
        self.conversation_history.append({"role": role, "content": content})
    
    def _prepare_messages(self):
        """
        Prepare the messages for the OpenAI API call.
        
        Returns:
            list: List of message dictionaries
        """
        # Start with the system message
        messages = [{"role": "system", "content": self.system_prompt}]
        
        # Add conversation history
        messages.extend(self.conversation_history)
        
        return messages
    
    def generate_response(self, user_message):
        """
        Generate a response using the GPT model.
        
        Args:
            user_message: The user's message to respond to
            
        Returns:
            str: The generated response
        """
        messages = self._prepare_messages()
        
        # Add the user message to history
        self.add_message("user", user_message)
        
        try:
            # Check if we're in mock mode
            if hasattr(config, 'MOCK_MODE') and config.MOCK_MODE:
                logger.info("MOCK MODE: Generating mock response")
                assistant_response = self._generate_mock_response(user_message)
            else:
                # Use the updated OpenAI client API
                response = self.client.chat.completions.create(
                    model=config.GPT_MODEL,
                    messages=messages,
                    max_tokens=config.MAX_TOKENS,
                    temperature=config.TEMPERATURE
                )
                
                assistant_response = response.choices[0].message.content
            
            # Add the response to history
            self.add_message("assistant", assistant_response)
            
            # Update state based on response
            self._update_state(assistant_response)
            
            return assistant_response
        
        except Exception as e:
            logger.error(f"Error generating response: {e}")
            
            # Use mock response in case of error
            mock_response = self._generate_mock_response(user_message)
            self.add_message("assistant", mock_response)
            self._update_state(mock_response)
            
            return mock_response
    
    def _generate_mock_response(self, user_message):
        """
        Generate a mock response for testing purposes.
        To be implemented by subclasses.
        
        Args:
            user_message: The user's message
            
        Returns:
            str: A mock response
        """
        return "This is a mock response. In a production environment, this would be generated by GPT-4."
    
    def _update_state(self, response):
        """
        Update the state based on the current response.
        To be implemented by subclasses.
        
        Args:
            response: The assistant's response
        """
        pass
    
    def get_conversation_summary(self):
        """
        Get a summary of the conversation.
        
        Returns:
            str: Summary of the conversation
        """
        return "\n".join([f"{msg['role']}: {msg['content']}" for msg in self.conversation_history])
    
    def get_state(self):
        """
        Get the current state of the conversation.
        
        Returns:
            dict: The current state
        """
        return self.state


class PatientAgent(ConversationAgent):
    """Agent for handling conversations with patients."""
    
    def __init__(self):
        """Initialize the PatientAgent with the appropriate system prompt."""
        super().__init__(prompts.PATIENT_AGENT_PROMPT)
        self.state = {
            "got_name": False,
            "got_dob": False,
            "got_insurance": False,
            "got_insurance_id": False,
            "got_address": False,
            "got_appointment_reason": False,
            "got_symptoms": False,
            "ready_for_hospital_call": False
        }
        self.patient_info = {
            "name": None,
            "dob": None,
            "insurance": None,
            "insurance_id": None,
            "address": None,
            "city": None,
            "state": None,
            "zip_code": None,
            "appointment_reason": None,
            "symptoms": None,
            "preferred_timeframe": None
        }
        self.conversation_counter = 0
    
    def generate_response(self, patient_message, known_info=""):
        """
        Generate a response to the patient's message.
        
        Args:
            patient_message: The patient's message
            known_info: Known information about the patient
            
        Returns:
            str: The generated response
        """
        # Format the user message using the template
        user_message = prompts.PATIENT_AGENT_USER_TEMPLATE.format(
            phone_number=known_info.get("phone_number", "Unknown"),
            known_info=known_info,
            conversation_history=self.get_conversation_summary(),
            patient_message=patient_message
        )
        
        return super().generate_response(user_message)
    
    def _generate_mock_response(self, user_message):
        """
        Generate a mock response for the patient agent.
        
        Args:
            user_message: The user's message
            
        Returns:
            str: A mock response
        """
        # Progress the conversation based on the number of exchanges
        self.conversation_counter += 1
        
        # First-time greeting
        if self.conversation_counter == 1:
            return "Hello! I'm Tofia, your healthcare assistant. I can help you schedule a medical appointment. May I have your name, please?"
        
        # Ask for DOB
        elif self.conversation_counter == 2:
            # Extract name from message if present
            if "my name is" in user_message.lower():
                name = user_message.lower().split("my name is")[1].strip().split(".")[0].title()
                self.patient_info["name"] = name
                self.state["got_name"] = True
            else:
                name = "there"
            return f"Thank you, {name}. For verification purposes, could you please provide your date of birth?"
        
        # Ask for insurance
        elif self.conversation_counter == 3:
            self.state["got_dob"] = True
            return "Great, thank you. What type of health insurance do you have?"
        
        # Ask about appointment reason
        elif self.conversation_counter == 4:
            self.state["got_insurance"] = True
            return "I've got that information. Now, what type of appointment would you like to schedule? For example, is it a regular check-up, a specialist visit, or something else?"
        
        # Ask about symptoms
        elif self.conversation_counter == 5:
            self.state["got_appointment_reason"] = True
            return "Can you briefly describe any symptoms or concerns you're experiencing that are related to this appointment request?"
        
        # Ask about preferred time
        elif self.conversation_counter == 6:
            self.state["got_symptoms"] = True
            return "Thank you for providing that information. Do you have any preferred days or times for your appointment?"
        
        # Conclude conversation
        elif self.conversation_counter >= 7:
            self.state["ready_for_hospital_call"] = True
            return "Thank you for providing all the necessary information. I'll contact the hospital to schedule your appointment and will send you an SMS confirmation once it's confirmed. Is there anything else you'd like me to know before I do that?"
        
        return "I understand. Let me help you with scheduling your appointment."
    
    def _update_state(self, response):
        """
        Update the state based on the current response.
        This looks for patterns in the conversation to determine what information has been collected.
        
        Args:
            response: The current response from the agent
        """
        # Get combined conversation history as a single string for pattern matching
        full_history = " ".join([msg["content"] for msg in self.conversation_history])
        
        # Check for name
        if not self.state["got_name"]:
            name_patterns = [
                r"(?i)my name is ([A-Za-z\s\-']+)",
                r"(?i)i(?:'|\s+)am ([A-Za-z\s\-']+)",
                r"(?i)this is ([A-Za-z\s\-']+)",
                r"(?i)call me ([A-Za-z\s\-']+)",
                r"(?i)patient(?:'s|s|\s+)name(?:\s+is|\s*:\s*)([A-Za-z\s\-']+)"
            ]
            
            for pattern in name_patterns:
                name_match = re.search(pattern, full_history)
                if name_match:
                    potential_name = name_match.group(1).strip()
                    # Perform basic validation to avoid catching non-name responses
                    if len(potential_name.split()) <= 4 and len(potential_name) > 2:
                        self.patient_info["name"] = potential_name
                        self.state["got_name"] = True
                        logger.info(f"Detected patient name: {potential_name}")
                        break
        
        # Check for date of birth
        if not self.state["got_dob"]:
            dob_patterns = [
                r"(?i)born (?:on\s+)?(\d{1,2}[/-]\d{1,2}[/-]\d{2,4})",
                r"(?i)birth(?:day|date)(?:\s+is|\s*:\s*)?\s*(\d{1,2}[/-]\d{1,2}[/-]\d{2,4})",
                r"(?i)dob(?:\s+is|\s*:\s*)?\s*(\d{1,2}[/-]\d{1,2}[/-]\d{2,4})",
                r"(?i)date of birth(?:\s+is|\s*:\s*)?\s*(\d{1,2}[/-]\d{1,2}[/-]\d{2,4})",
                r"(?i)i was born (?:on\s+)?(\d{1,2}[/-]\d{1,2}[/-]\d{2,4})",
                r"(?i)(\d{1,2}[/-]\d{1,2}[/-]\d{2,4})"  # Last resort, just try to find a date format
            ]
            
            for pattern in dob_patterns:
                dob_match = re.search(pattern, full_history)
                if dob_match:
                    potential_dob = dob_match.group(1).strip()
                    self.patient_info["dob"] = potential_dob
                    self.state["got_dob"] = True
                    logger.info(f"Detected patient DOB: {potential_dob}")
                    break
        
        # Check for insurance
        if not self.state["got_insurance"]:
            insurance_patterns = [
                r"(?i)(?:my\s+)?insurance(?:\s+is|\s+provider(?:\s+is)?|\s*:\s*)?\s*([A-Za-z\s\-']+(?:health|insurance|medical|blue|shield|cross|aetna|cigna|united|humana|kaiser|medicaid|medicare)(?:\s*[A-Za-z\s\-']+)?)",
                r"(?i)(?:i have|i('|'|\s+)m on|i use)\s+([A-Za-z\s\-']+(?:health|insurance|medical|blue|shield|cross|aetna|cigna|united|humana|kaiser|medicaid|medicare)(?:\s*[A-Za-z\s\-']+)?)",
                r"(?i)(?:with|through)\s+([A-Za-z\s\-']+(?:health|insurance|medical|blue|shield|cross|aetna|cigna|united|humana|kaiser|medicaid|medicare)(?:\s*[A-Za-z\s\-']+)?)"
            ]
            
            for pattern in insurance_patterns:
                insurance_match = re.search(pattern, full_history)
                if insurance_match:
                    potential_insurance = insurance_match.group(1).strip()
                    if len(potential_insurance) > 2:
                        self.patient_info["insurance"] = potential_insurance
                        self.state["got_insurance"] = True
                        logger.info(f"Detected patient insurance: {potential_insurance}")
                        break
                        
        # Check for insurance ID
        if not self.state["got_insurance_id"]:
            insurance_id_patterns = [
                r"(?i)(?:insurance|policy|member|id)(?:\s+id|\s+card|\s+number)?(?:\s+is|\s*:\s*)?\s*([A-Za-z0-9\-]+)",
                r"(?i)(?:my\s+)?(?:insurance|policy|member|id)(?:\s+id|\s+card|\s+number)?\s+(?:is|=)\s*([A-Za-z0-9\-]+)",
                r"(?i)(?:insurance|policy|member|id)(?:\s+id|\s+card|\s+number)?[:\s]+([A-Za-z0-9\-]{5,20})"
            ]
            
            for pattern in insurance_id_patterns:
                id_match = re.search(pattern, full_history)
                if id_match:
                    potential_id = id_match.group(1).strip()
                    # Basic validation - IDs are typically alphanumeric and at least a few chars
                    if len(potential_id) >= 4:
                        self.patient_info["insurance_id"] = potential_id
                        self.state["got_insurance_id"] = True
                        logger.info(f"Detected patient insurance ID: {potential_id}")
                        break
                        
        # Check for address information
        if not self.state["got_address"]:
            # Address pattern (street address)
            address_patterns = [
                r"(?i)(?:my\s+)?address(?:\s+is|\s*:\s*)?\s*([0-9]+\s+[A-Za-z0-9\s\-'.]+(?:street|st|avenue|ave|road|rd|boulevard|blvd|lane|ln|drive|dr|way|circle|cir|court|ct|place|pl|terrace|ter)(?:\s+[A-Za-z0-9\s\-'.#]+)?)",
                r"(?i)(?:i live at|located at)\s+([0-9]+\s+[A-Za-z0-9\s\-'.]+(?:street|st|avenue|ave|road|rd|boulevard|blvd|lane|ln|drive|dr|way|circle|cir|court|ct|place|pl|terrace|ter)(?:\s+[A-Za-z0-9\s\-'.#]+)?)"
            ]
            
            for pattern in address_patterns:
                address_match = re.search(pattern, full_history)
                if address_match:
                    self.patient_info["address"] = address_match.group(1).strip()
                    self.state["got_address"] = True
                    logger.info(f"Detected patient address: {self.patient_info['address']}")
                    break
            
            # City pattern
            city_patterns = [
                r"(?i)(?:in|of|from|city(?:\s+of)?|city(?:\s+is)?:?)\s+([A-Za-z\s\-'.]+),\s*(?:[A-Z]{2}|[A-Za-z]+)",
                r"(?i)city(?:\s+is|\s*:\s*)?\s*([A-Za-z\s\-'.]+)"
            ]
            
            for pattern in city_patterns:
                city_match = re.search(pattern, full_history)
                if city_match:
                    potential_city = city_match.group(1).strip()
                    if len(potential_city) > 2 and all(not c.isdigit() for c in potential_city):
                        self.patient_info["city"] = potential_city
                        logger.info(f"Detected patient city: {potential_city}")
                        break
            
            # State pattern
            state_patterns = [
                r"(?i)[A-Za-z\s\-'.]+,\s*([A-Z]{2})\s*\d{5}",  # City, ST ZIP
                r"(?i)state(?:\s+is|\s+of|\s*:\s*)?\s*([A-Za-z]{2,14})",
                r"(?i)in\s+([A-Z]{2})\b"  # In CA
            ]
            
            for pattern in state_patterns:
                state_match = re.search(pattern, full_history)
                if state_match:
                    potential_state = state_match.group(1).strip().upper()
                    if len(potential_state) == 2 or potential_state.lower() in ['california', 'texas', 'florida', 'new york', 'washington']:
                        # Convert full state names to abbreviations if needed
                        state_abbr_map = {
                            'california': 'CA', 'texas': 'TX', 'florida': 'FL', 
                            'new york': 'NY', 'washington': 'WA'
                        }
                        potential_state = state_abbr_map.get(potential_state.lower(), potential_state)
                        if len(potential_state) > 2:
                            potential_state = potential_state[:2].upper()
                            
                        self.patient_info["state"] = potential_state
                        logger.info(f"Detected patient state: {potential_state}")
                        break
            
            # ZIP code pattern
            zip_patterns = [
                r"(?i)zip(?:\s+code|\s*:\s*)?\s*(\d{5}(?:-\d{4})?)",
                r"(?i)[A-Za-z\s\-'.]+,\s*[A-Z]{2}\s*(\d{5}(?:-\d{4})?)"  # City, ST ZIP
            ]
            
            for pattern in zip_patterns:
                zip_match = re.search(pattern, full_history)
                if zip_match:
                    self.patient_info["zip_code"] = zip_match.group(1).strip()
                    logger.info(f"Detected patient ZIP code: {self.patient_info['zip_code']}")
                    break
                    
            # If we have at least address and city or state or zip, consider the address information sufficient
            if self.patient_info["address"] and (self.patient_info["city"] or self.patient_info["state"] or self.patient_info["zip_code"]):
                self.state["got_address"] = True
        
        # Check for appointment reason
        if not self.state["got_appointment_reason"]:
            reason_patterns = [
                r"(?i)(?:appointment for|reason for|need to see|appointment is for|reason is|concerning|regarding|about) ([^.?!]+[.?!])",
                r"(?i)(?:i have|i('|'|\s+)m on|i use)\s+([^.?!]+[.?!])",
                r"(?i)(?:symptoms include|symptoms are|problem is|issue is|condition is) ([^.?!]+[.?!])"
            ]
            
            for pattern in reason_patterns:
                reason_match = re.search(pattern, full_history)
                if reason_match:
                    potential_reason = reason_match.group(1).strip()
                    if len(potential_reason) > 5 and len(potential_reason.split()) > 2:
                        self.patient_info["appointment_reason"] = potential_reason
                        self.state["got_appointment_reason"] = True
                        logger.info(f"Detected appointment reason: {potential_reason}")
                        break
        
        # If we have all essential information, mark as ready for hospital call
        required_info = ["name", "dob", "insurance", "appointment_reason"]
        if all(self.patient_info[info] for info in required_info):
            self.state["ready_for_hospital_call"] = True
            logger.info("Patient information complete - ready for hospital call")
            
        # Debug log the current patient info state
        logger.debug(f"Current patient info: {self.patient_info}")
        logger.debug(f"Current state: {self.state}")
    
    def get_appointment_details(self):
        """
        Get the confirmed appointment details.
        
        Returns:
            dict: The appointment details if confirmed, None otherwise
        """
        if self.state["ready_for_hospital_call"]:
            return self.patient_info
        return None


class HospitalAgent(ConversationAgent):
    """Agent for handling conversations with hospital receptionists."""
    
    def __init__(self, patient_info):
        """
        Initialize the HospitalAgent with the appropriate system prompt.
        
        Args:
            patient_info: Dictionary containing patient information
        """
        super().__init__(prompts.HOSPITAL_AGENT_PROMPT)
        self.patient_info = patient_info
        self.state = {
            "appointment_confirmed": False,
            "got_appointment_date": False,
            "got_appointment_time": False,
            "got_doctor_name": False
        }
        self.appointment_info = {
            "date": None,
            "time": None,
            "doctor": None,
            "special_instructions": None
        }
        self.conversation_counter = 0
    
    def generate_response(self, receptionist_message):
        """
        Generate a response to the receptionist's message.
        
        Args:
            receptionist_message: The receptionist's message
            
        Returns:
            str: The generated response
        """
        # Format the user message using the template
        user_message = prompts.HOSPITAL_AGENT_USER_TEMPLATE.format(
            name=self.patient_info.get("name", "Unknown"),
            dob=self.patient_info.get("dob", "Unknown"),
            insurance=self.patient_info.get("insurance", "Unknown"),
            reason=self.patient_info.get("appointment_reason", "medical appointment"),
            symptoms=self.patient_info.get("symptoms", "Unknown"),
            timeframe=self.patient_info.get("preferred_timeframe", "as soon as possible"),
            conversation_history=self.get_conversation_summary(),
            receptionist_message=receptionist_message
        )
        
        return super().generate_response(user_message)
    
    def _generate_mock_response(self, user_message):
        """
        Generate a mock response for the hospital agent.
        
        Args:
            user_message: The user's message
            
        Returns:
            str: A mock response
        """
        # Progress the conversation based on the number of exchanges
        self.conversation_counter += 1
        
        # Introduction
        if self.conversation_counter == 1:
            return f"Hello, this is Tofia calling from the automated appointment scheduling service. I'd like to schedule an appointment for {self.patient_info.get('name', 'a patient')}."
        
        # Provide patient information
        elif self.conversation_counter == 2:
            return f"The patient is experiencing {self.patient_info.get('symptoms', 'some symptoms')} and needs a {self.patient_info.get('appointment_reason', 'medical appointment')}. Their insurance is {self.patient_info.get('insurance', 'Unknown')}."
        
        # Respond to available slots
        elif self.conversation_counter == 3:
            self.state["got_appointment_date"] = True
            self.state["got_appointment_time"] = True
            self.appointment_info["date"] = "tomorrow"
            self.appointment_info["time"] = "2:30 PM"
            return "Tomorrow at 2:30 PM would work perfectly for the patient. Thank you."
        
        # Confirm details and doctor
        elif self.conversation_counter == 4:
            self.state["got_doctor_name"] = True
            self.appointment_info["doctor"] = "Dr. Smith"
            self.state["appointment_confirmed"] = True
            return "Great, I'll confirm the appointment with Dr. Smith tomorrow at 2:30 PM. I'll let the patient know. Thank you for your help."
        
        return "Thank you for your assistance with scheduling this appointment."
    
    def _update_state(self, response):
        """
        Update the state based on the current response.
        To be implemented by subclasses.
        
        Args:
            response: The assistant's response
        """
        # In mock mode, state is updated by the _generate_mock_response method
        if hasattr(config, 'MOCK_MODE') and config.MOCK_MODE:
            return
            
        try:
            # Look for appointment date in conversation
            if not self.state["got_appointment_date"] and len(self.conversation_history) >= 2:
                patient_message = self.conversation_history[-2]["content"].lower()
                appointment_date_patterns = ["schedule", "appointment", "date"]
                if any(pattern in patient_message for pattern in appointment_date_patterns):
                    # This extracts dates in various formats
                    import re
                    # Match various date formats
                    date_patterns = [
                        r'\b\d{1,2}/\d{1,2}/\d{2,4}\b',  # MM/DD/YYYY or DD/MM/YYYY
                        r'\b\d{1,2}-\d{1,2}-\d{2,4}\b',   # MM-DD-YYYY or DD-MM-YYYY
                        r'\b(?:january|february|march|april|may|june|july|august|september|october|november|december|jan|feb|mar|apr|jun|jul|aug|sep|sept|oct|nov|dec)[.,\s]+\d{1,2}(?:st|nd|rd|th)?[.,\s]+\d{2,4}\b',  # Month DD, YYYY
                    ]
                    for pattern in date_patterns:
                        matches = re.findall(pattern, patient_message, re.IGNORECASE)
                        if matches:
                            self.appointment_info["date"] = matches[0]
                            self.state["got_appointment_date"] = True
                            logger.info(f"Extracted appointment date: {matches[0]}")
                            break
            
            # Look for appointment time
            if not self.state["got_appointment_time"] and len(self.conversation_history) >= 2:
                patient_message = self.conversation_history[-2]["content"].lower()
                appointment_time_patterns = ["at", "time"]
                if any(pattern in patient_message for pattern in appointment_time_patterns):
                    # Extract the time (simplified)
                    words = patient_message.split()
                    for idx, word in enumerate(words):
                        if any(pattern in word for pattern in appointment_time_patterns) and idx < len(words) - 1:
                            # Take words after the time keyword, up to 5 words
                            potential_time = " ".join(words[idx+1:idx+6]).rstrip(".,!?")
                            if potential_time:
                                self.appointment_info["time"] = potential_time
                                self.state["got_appointment_time"] = True
                                logger.info(f"Extracted appointment time: {potential_time}")
                                break
            
            # Look for doctor name
            if not self.state["got_doctor_name"] and len(self.conversation_history) >= 2:
                patient_message = self.conversation_history[-2]["content"].lower()
                doctor_name_patterns = ["doctor", "dr."]
                if any(pattern in patient_message for pattern in doctor_name_patterns):
                    # Extract doctor name (simplified)
                    words = patient_message.split()
                    for idx, word in enumerate(words):
                        if any(pattern in word for pattern in doctor_name_patterns) and idx < len(words) - 1:
                            # Take words after the doctor keyword, up to 5 words
                            potential_doctor = " ".join(words[idx+1:idx+6]).rstrip(".,!?")
                            if potential_doctor:
                                self.appointment_info["doctor"] = potential_doctor
                                self.state["got_doctor_name"] = True
                                logger.info(f"Extracted doctor name: {potential_doctor}")
                                break
            
            # Check if appointment is confirmed
            if (self.state["got_appointment_date"] and self.state["got_appointment_time"]):
                self.state["appointment_confirmed"] = True
                logger.info("Appointment confirmed")
                
        except Exception as e:
            logger.error(f"Error in HospitalAgent._update_state: {e}")
            # Don't let an error in state update break the whole flow
    
    def get_appointment_details(self):
        """
        Get the confirmed appointment details.
        
        Returns:
            dict: The appointment details if confirmed, None otherwise
        """
        if self.state["appointment_confirmed"]:
            return self.appointment_info
        return None
