"""
Conversation Agents module for Tofia Voice Assistant.
Implements PatientAgent and HospitalAgent for handling conversations with patients and hospital staff.
"""
import logging
import openai
import json
import config
import prompts

logger = logging.getLogger(__name__)

class ConversationAgent:
    """Base class for conversation agents."""
    
    def __init__(self, system_prompt):
        """
        Initialize the conversation agent.
        
        Args:
            system_prompt: System message for the GPT model
        """
        self.system_prompt = system_prompt
        self.conversation_history = []
        self.state = {}
        
        # Configure OpenAI API key
        openai.api_key = config.OPENAI_API_KEY
        self.client = openai.OpenAI(api_key=config.OPENAI_API_KEY)
    
    def add_message(self, role, content):
        """
        Add a message to the conversation history.
        
        Args:
            role: The role ("system", "user", "assistant")
            content: The message content
        """
        self.conversation_history.append({"role": role, "content": content})
    
    def _prepare_messages(self):
        """
        Prepare the messages for the OpenAI API call.
        
        Returns:
            list: List of message dictionaries
        """
        # Start with the system message
        messages = [{"role": "system", "content": self.system_prompt}]
        
        # Add conversation history
        messages.extend(self.conversation_history)
        
        return messages
    
    def generate_response(self, user_message):
        """
        Generate a response using the GPT model.
        
        Args:
            user_message: The user's message to respond to
            
        Returns:
            str: The generated response
        """
        messages = self._prepare_messages()
        
        # Add the user message to history
        self.add_message("user", user_message)
        
        try:
            # Check if we're in mock mode
            if hasattr(config, 'MOCK_MODE') and config.MOCK_MODE:
                logger.info("MOCK MODE: Generating mock response")
                assistant_response = self._generate_mock_response(user_message)
            else:
                # Use the updated OpenAI client API
                response = self.client.chat.completions.create(
                    model=config.GPT_MODEL,
                    messages=messages,
                    max_tokens=config.MAX_TOKENS,
                    temperature=config.TEMPERATURE
                )
                
                assistant_response = response.choices[0].message.content
            
            # Add the response to history
            self.add_message("assistant", assistant_response)
            
            # Update state based on response
            self._update_state(assistant_response)
            
            return assistant_response
        
        except Exception as e:
            logger.error(f"Error generating response: {e}")
            
            # Use mock response in case of error
            mock_response = self._generate_mock_response(user_message)
            self.add_message("assistant", mock_response)
            self._update_state(mock_response)
            
            return mock_response
    
    def _generate_mock_response(self, user_message):
        """
        Generate a mock response for testing purposes.
        To be implemented by subclasses.
        
        Args:
            user_message: The user's message
            
        Returns:
            str: A mock response
        """
        return "This is a mock response. In a production environment, this would be generated by GPT-4."
    
    def _update_state(self, response):
        """
        Update the state based on the current response.
        To be implemented by subclasses.
        
        Args:
            response: The assistant's response
        """
        pass
    
    def get_conversation_summary(self):
        """
        Get a summary of the conversation.
        
        Returns:
            str: Summary of the conversation
        """
        return "\n".join([f"{msg['role']}: {msg['content']}" for msg in self.conversation_history])
    
    def get_state(self):
        """
        Get the current state of the conversation.
        
        Returns:
            dict: The current state
        """
        return self.state


class PatientAgent(ConversationAgent):
    """Agent for handling conversations with patients."""
    
    def __init__(self):
        """Initialize the PatientAgent with the appropriate system prompt."""
        super().__init__(prompts.PATIENT_AGENT_PROMPT)
        self.state = {
            "got_name": False,
            "got_dob": False,
            "got_insurance": False,
            "got_appointment_reason": False,
            "got_symptoms": False,
            "ready_for_hospital_call": False
        }
        self.patient_info = {
            "name": None,
            "dob": None,
            "insurance": None,
            "appointment_reason": None,
            "symptoms": None,
            "preferred_timeframe": None
        }
        self.conversation_counter = 0
    
    def generate_response(self, patient_message, known_info=""):
        """
        Generate a response to the patient's message.
        
        Args:
            patient_message: The patient's message
            known_info: Known information about the patient
            
        Returns:
            str: The generated response
        """
        # Format the user message using the template
        user_message = prompts.PATIENT_AGENT_USER_TEMPLATE.format(
            phone_number=known_info.get("phone_number", "Unknown"),
            known_info=known_info,
            conversation_history=self.get_conversation_summary(),
            patient_message=patient_message
        )
        
        return super().generate_response(user_message)
    
    def _generate_mock_response(self, user_message):
        """
        Generate a mock response for the patient agent.
        
        Args:
            user_message: The user's message
            
        Returns:
            str: A mock response
        """
        # Progress the conversation based on the number of exchanges
        self.conversation_counter += 1
        
        # First-time greeting
        if self.conversation_counter == 1:
            return "Hello! I'm Tofia, your healthcare assistant. I can help you schedule a medical appointment. May I have your name, please?"
        
        # Ask for DOB
        elif self.conversation_counter == 2:
            # Extract name from message if present
            if "my name is" in user_message.lower():
                name = user_message.lower().split("my name is")[1].strip().split(".")[0].title()
                self.patient_info["name"] = name
                self.state["got_name"] = True
            else:
                name = "there"
            return f"Thank you, {name}. For verification purposes, could you please provide your date of birth?"
        
        # Ask for insurance
        elif self.conversation_counter == 3:
            self.state["got_dob"] = True
            return "Great, thank you. What type of health insurance do you have?"
        
        # Ask about appointment reason
        elif self.conversation_counter == 4:
            self.state["got_insurance"] = True
            return "I've got that information. Now, what type of appointment would you like to schedule? For example, is it a regular check-up, a specialist visit, or something else?"
        
        # Ask about symptoms
        elif self.conversation_counter == 5:
            self.state["got_appointment_reason"] = True
            return "Can you briefly describe any symptoms or concerns you're experiencing that are related to this appointment request?"
        
        # Ask about preferred time
        elif self.conversation_counter == 6:
            self.state["got_symptoms"] = True
            return "Thank you for providing that information. Do you have any preferred days or times for your appointment?"
        
        # Conclude conversation
        elif self.conversation_counter >= 7:
            self.state["ready_for_hospital_call"] = True
            return "Thank you for providing all the necessary information. I'll contact the hospital to schedule your appointment and will send you an SMS confirmation once it's confirmed. Is there anything else you'd like me to know before I do that?"
        
        return "I understand. Let me help you with scheduling your appointment."
    
    def _update_state(self, response):
        """
        Update the state based on the current response.
        
        Args:
            response: The assistant's response
        """
        # In mock mode, state is updated by the _generate_mock_response method
        if hasattr(config, 'MOCK_MODE') and config.MOCK_MODE:
            return
            
        # Check for name
        if not self.state["got_name"] and ("my name is" in self.conversation_history[-2]["content"].lower() or 
                                         "name's" in self.conversation_history[-2]["content"].lower()):
            # Extract name from patient message (simplified)
            patient_message = self.conversation_history[-2]["content"].lower()
            if "my name is" in patient_message:
                self.patient_info["name"] = patient_message.split("my name is")[1].strip().split(".")[0].title()
                self.state["got_name"] = True
            elif "name's" in patient_message:
                self.patient_info["name"] = patient_message.split("name's")[1].strip().split(".")[0].title()
                self.state["got_name"] = True
        
        # Check for DOB
        if not self.state["got_dob"] and "birth" in self.conversation_history[-2]["content"].lower():
            # This is a simplified extraction, in reality would use more robust parsing
            self.state["got_dob"] = True
        
        # Check for insurance
        if not self.state["got_insurance"] and "insurance" in self.conversation_history[-2]["content"].lower():
            self.state["got_insurance"] = True
        
        # Check for appointment reason
        if not self.state["got_appointment_reason"] and any(word in self.conversation_history[-2]["content"].lower() 
                                                         for word in ["appointment", "schedule", "see doctor"]):
            self.state["got_appointment_reason"] = True
        
        # Check if ready for hospital call
        if (self.state["got_name"] and self.state["got_dob"] and 
            self.state["got_insurance"] and self.state["got_appointment_reason"]):
            self.state["ready_for_hospital_call"] = True


class HospitalAgent(ConversationAgent):
    """Agent for handling conversations with hospital receptionists."""
    
    def __init__(self, patient_info):
        """
        Initialize the HospitalAgent with the appropriate system prompt.
        
        Args:
            patient_info: Dictionary containing patient information
        """
        super().__init__(prompts.HOSPITAL_AGENT_PROMPT)
        self.patient_info = patient_info
        self.state = {
            "appointment_confirmed": False,
            "got_appointment_date": False,
            "got_appointment_time": False,
            "got_doctor_name": False
        }
        self.appointment_info = {
            "date": None,
            "time": None,
            "doctor": None,
            "special_instructions": None
        }
        self.conversation_counter = 0
    
    def generate_response(self, receptionist_message):
        """
        Generate a response to the receptionist's message.
        
        Args:
            receptionist_message: The receptionist's message
            
        Returns:
            str: The generated response
        """
        # Format the user message using the template
        user_message = prompts.HOSPITAL_AGENT_USER_TEMPLATE.format(
            name=self.patient_info.get("name", "Unknown"),
            dob=self.patient_info.get("dob", "Unknown"),
            insurance=self.patient_info.get("insurance", "Unknown"),
            reason=self.patient_info.get("appointment_reason", "medical appointment"),
            symptoms=self.patient_info.get("symptoms", "Unknown"),
            timeframe=self.patient_info.get("preferred_timeframe", "as soon as possible"),
            conversation_history=self.get_conversation_summary(),
            receptionist_message=receptionist_message
        )
        
        return super().generate_response(user_message)
    
    def _generate_mock_response(self, user_message):
        """
        Generate a mock response for the hospital agent.
        
        Args:
            user_message: The user's message
            
        Returns:
            str: A mock response
        """
        # Progress the conversation based on the number of exchanges
        self.conversation_counter += 1
        
        # Introduction
        if self.conversation_counter == 1:
            return f"Hello, this is Tofia calling from the automated appointment scheduling service. I'd like to schedule an appointment for {self.patient_info.get('name', 'a patient')}."
        
        # Provide patient information
        elif self.conversation_counter == 2:
            return f"The patient is experiencing {self.patient_info.get('symptoms', 'some symptoms')} and needs a {self.patient_info.get('appointment_reason', 'medical appointment')}. Their insurance is {self.patient_info.get('insurance', 'Unknown')}."
        
        # Respond to available slots
        elif self.conversation_counter == 3:
            self.state["got_appointment_date"] = True
            self.state["got_appointment_time"] = True
            self.appointment_info["date"] = "tomorrow"
            self.appointment_info["time"] = "2:30 PM"
            return "Tomorrow at 2:30 PM would work perfectly for the patient. Thank you."
        
        # Confirm details and doctor
        elif self.conversation_counter == 4:
            self.state["got_doctor_name"] = True
            self.appointment_info["doctor"] = "Dr. Smith"
            self.state["appointment_confirmed"] = True
            return "Great, I'll confirm the appointment with Dr. Smith tomorrow at 2:30 PM. I'll let the patient know. Thank you for your help."
        
        return "Thank you for your assistance with scheduling this appointment."
    
    def _update_state(self, response):
        """
        Update the state based on the current response.
        
        Args:
            response: The assistant's response
        """
        # In mock mode, state is updated by the _generate_mock_response method
        if hasattr(config, 'MOCK_MODE') and config.MOCK_MODE:
            return
            
        # Look for appointment date in conversation
        if not self.state["got_appointment_date"] and any(word in self.conversation_history[-2]["content"].lower() 
                                                       for word in ["schedule", "appointment", "date"]):
            # This is a simplified extraction, in reality would use more robust parsing like NER
            self.state["got_appointment_date"] = True
            
            # Extract the date from the conversation (simplified)
            last_message = self.conversation_history[-2]["content"].lower()
            # Very basic date extraction - in a real system would use a date parser
            if "on " in last_message and " at " in last_message:
                try:
                    date_part = last_message.split("on ")[1].split(" at ")[0].strip()
                    self.appointment_info["date"] = date_part
                except:
                    pass
        
        # Look for appointment time
        if not self.state["got_appointment_time"] and " at " in self.conversation_history[-2]["content"].lower():
            self.state["got_appointment_time"] = True
            
            # Extract the time (simplified)
            last_message = self.conversation_history[-2]["content"].lower()
            if " at " in last_message:
                try:
                    time_part = last_message.split(" at ")[1].split(".")[0].strip()
                    self.appointment_info["time"] = time_part
                except:
                    pass
        
        # Look for doctor name
        if not self.state["got_doctor_name"] and "doctor" in self.conversation_history[-2]["content"].lower():
            self.state["got_doctor_name"] = True
            
            # Extract doctor name (simplified)
            # In a real system would use NER to extract names
            
        # Check if appointment is confirmed
        if (self.state["got_appointment_date"] and self.state["got_appointment_time"]):
            self.state["appointment_confirmed"] = True
    
    def get_appointment_details(self):
        """
        Get the confirmed appointment details.
        
        Returns:
            dict: The appointment details if confirmed, None otherwise
        """
        if self.state["appointment_confirmed"]:
            return self.appointment_info
        return None
