"""
Conversation Agents module for Tofia Voice Assistant.
Implements PatientAgent and HospitalAgent for handling conversations with patients and hospital staff.
"""
import logging
import openai
import json
import config
import prompts
import re

logger = logging.getLogger(__name__)

class ConversationAgent:
    """Base class for conversation agents."""
    
    def __init__(self, system_prompt):
        """
        Initialize the conversation agent.
        
        Args:
            system_prompt: System message for the GPT model
        """
        self.system_prompt = system_prompt
        self.conversation_history = []
        self.state = {}
        
        # Configure OpenAI API key
        openai.api_key = config.OPENAI_API_KEY
        self.client = openai.OpenAI(api_key=config.OPENAI_API_KEY)
    
    def add_message(self, role, content):
        """
        Add a message to the conversation history.
        
        Args:
            role: The role ("system", "user", "assistant")
            content: The message content
        """
        self.conversation_history.append({"role": role, "content": content})
    
    def _prepare_messages(self):
        """
        Prepare the messages for the OpenAI API call.
        
        Returns:
            list: List of message dictionaries
        """
        # Start with the system message
        messages = [{"role": "system", "content": self.system_prompt}]
        
        # Add conversation history
        messages.extend(self.conversation_history)
        
        return messages
    
    def generate_response(self, user_message):
        """
        Generate a response using the GPT model.
        
        Args:
            user_message: The user's message to respond to
            
        Returns:
            str: The generated response
        """
        messages = self._prepare_messages()
        
        # Add the user message to history
        self.add_message("user", user_message)
        
        try:
            # Check if we're in mock mode
            if hasattr(config, 'MOCK_MODE') and config.MOCK_MODE:
                logger.info("MOCK MODE: Generating mock response")
                assistant_response = self._generate_mock_response(user_message)
            else:
                # Use the updated OpenAI client API
                response = self.client.chat.completions.create(
                    model=config.GPT_MODEL,
                    messages=messages,
                    max_tokens=config.MAX_TOKENS,
                    temperature=config.TEMPERATURE
                )
                
                assistant_response = response.choices[0].message.content
            
            # Add the response to history
            self.add_message("assistant", assistant_response)
            
            # Update state based on response
            self._update_state(assistant_response)
            
            return assistant_response
        
        except Exception as e:
            logger.error(f"Error generating response: {e}")
            
            # Use mock response in case of error
            mock_response = self._generate_mock_response(user_message)
            self.add_message("assistant", mock_response)
            self._update_state(mock_response)
            
            return mock_response
    
    def _generate_mock_response(self, user_message):
        """
        Generate a mock response for testing purposes.
        To be implemented by subclasses.
        
        Args:
            user_message: The user's message
            
        Returns:
            str: A mock response
        """
        return "This is a mock response. In a production environment, this would be generated by GPT-4."
    
    def _update_state(self, response):
        """
        Update the state based on the current response.
        To be implemented by subclasses.
        
        Args:
            response: The assistant's response
        """
        pass
    
    def get_conversation_summary(self):
        """
        Get a summary of the conversation.
        
        Returns:
            str: Summary of the conversation
        """
        return "\n".join([f"{msg['role']}: {msg['content']}" for msg in self.conversation_history])
    
    def get_state(self):
        """
        Get the current state of the conversation.
        
        Returns:
            dict: The current state
        """
        return self.state


class PatientAgent(ConversationAgent):
    """Agent for handling conversations with patients."""
    
    def __init__(self):
        """Initialize the PatientAgent with the appropriate system prompt."""
        super().__init__(prompts.PATIENT_AGENT_PROMPT)
        self.state = {
            "got_name": False,
            "got_dob": False,
            "got_insurance": False,
            "got_appointment_reason": False,
            "got_symptoms": False,
            "ready_for_hospital_call": False
        }
        self.patient_info = {
            "name": None,
            "dob": None,
            "insurance": None,
            "appointment_reason": None,
            "symptoms": None,
            "preferred_timeframe": None
        }
        self.conversation_counter = 0
    
    def generate_response(self, patient_message, known_info=""):
        """
        Generate a response to the patient's message.
        
        Args:
            patient_message: The patient's message
            known_info: Known information about the patient
            
        Returns:
            str: The generated response
        """
        # Format the user message using the template
        user_message = prompts.PATIENT_AGENT_USER_TEMPLATE.format(
            phone_number=known_info.get("phone_number", "Unknown"),
            known_info=known_info,
            conversation_history=self.get_conversation_summary(),
            patient_message=patient_message
        )
        
        return super().generate_response(user_message)
    
    def _generate_mock_response(self, user_message):
        """
        Generate a mock response for the patient agent.
        
        Args:
            user_message: The user's message
            
        Returns:
            str: A mock response
        """
        # Progress the conversation based on the number of exchanges
        self.conversation_counter += 1
        
        # First-time greeting
        if self.conversation_counter == 1:
            return "Hello! I'm Tofia, your healthcare assistant. I can help you schedule a medical appointment. May I have your name, please?"
        
        # Ask for DOB
        elif self.conversation_counter == 2:
            # Extract name from message if present
            if "my name is" in user_message.lower():
                name = user_message.lower().split("my name is")[1].strip().split(".")[0].title()
                self.patient_info["name"] = name
                self.state["got_name"] = True
            else:
                name = "there"
            return f"Thank you, {name}. For verification purposes, could you please provide your date of birth?"
        
        # Ask for insurance
        elif self.conversation_counter == 3:
            self.state["got_dob"] = True
            return "Great, thank you. What type of health insurance do you have?"
        
        # Ask about appointment reason
        elif self.conversation_counter == 4:
            self.state["got_insurance"] = True
            return "I've got that information. Now, what type of appointment would you like to schedule? For example, is it a regular check-up, a specialist visit, or something else?"
        
        # Ask about symptoms
        elif self.conversation_counter == 5:
            self.state["got_appointment_reason"] = True
            return "Can you briefly describe any symptoms or concerns you're experiencing that are related to this appointment request?"
        
        # Ask about preferred time
        elif self.conversation_counter == 6:
            self.state["got_symptoms"] = True
            return "Thank you for providing that information. Do you have any preferred days or times for your appointment?"
        
        # Conclude conversation
        elif self.conversation_counter >= 7:
            self.state["ready_for_hospital_call"] = True
            return "Thank you for providing all the necessary information. I'll contact the hospital to schedule your appointment and will send you an SMS confirmation once it's confirmed. Is there anything else you'd like me to know before I do that?"
        
        return "I understand. Let me help you with scheduling your appointment."
    
    def _update_state(self, response):
        """
        Update the state based on the current response.
        
        Args:
            response: The assistant's response
        """
        # In mock mode, state is updated by the _generate_mock_response method
        if hasattr(config, 'MOCK_MODE') and config.MOCK_MODE:
            return
            
        try:
            # Check for name
            if not self.state["got_name"] and len(self.conversation_history) >= 2:
                patient_message = self.conversation_history[-2]["content"].lower()
                # More robust name detection
                name_patterns = ["my name is", "name's", "i'm ", "i am ", "call me"]
                for pattern in name_patterns:
                    if pattern in patient_message:
                        words = patient_message.split(pattern)[1].strip().split()
                        # Extract up to 3 words as the name
                        potential_name = " ".join(words[:3]).rstrip(".,!?").title()
                        if potential_name and len(potential_name) > 1:
                            self.patient_info["name"] = potential_name
                            self.state["got_name"] = True
                            logger.info(f"Extracted patient name: {potential_name}")
                            break
            
            # Check for DOB
            if not self.state["got_dob"] and len(self.conversation_history) >= 2:
                patient_message = self.conversation_history[-2]["content"].lower()
                dob_patterns = ["birth", "born", "dob", "birthday"]
                if any(pattern in patient_message for pattern in dob_patterns):
                    # This extracts dates in various formats
                    import re
                    # Match various date formats
                    date_patterns = [
                        r'\b\d{1,2}/\d{1,2}/\d{2,4}\b',  # MM/DD/YYYY or DD/MM/YYYY
                        r'\b\d{1,2}-\d{1,2}-\d{2,4}\b',   # MM-DD-YYYY or DD-MM-YYYY
                        r'\b(?:january|february|march|april|may|june|july|august|september|october|november|december|jan|feb|mar|apr|jun|jul|aug|sep|sept|oct|nov|dec)[.,\s]+\d{1,2}(?:st|nd|rd|th)?[.,\s]+\d{2,4}\b',  # Month DD, YYYY
                    ]
                    for pattern in date_patterns:
                        matches = re.findall(pattern, patient_message, re.IGNORECASE)
                        if matches:
                            self.patient_info["dob"] = matches[0]
                            self.state["got_dob"] = True
                            logger.info(f"Extracted patient DOB: {matches[0]}")
                            break
            
            # Check for insurance
            if not self.state["got_insurance"] and len(self.conversation_history) >= 2:
                patient_message = self.conversation_history[-2]["content"].lower()
                insurance_patterns = ["insurance", "insured", "coverage", "plan", "provider"]
                if any(pattern in patient_message for pattern in insurance_patterns):
                    # Simplified extraction of insurance information
                    words = patient_message.split()
                    for idx, word in enumerate(words):
                        if any(pattern in word for pattern in insurance_patterns) and idx < len(words) - 1:
                            # Take words after the insurance keyword, up to 5 words
                            potential_insurance = " ".join(words[idx+1:idx+6]).rstrip(".,!?")
                            if potential_insurance:
                                self.patient_info["insurance"] = potential_insurance
                                self.state["got_insurance"] = True
                                logger.info(f"Extracted insurance info: {potential_insurance}")
                                break
                                
            # Check for appointment reason
            if not self.state["got_appointment_reason"] and len(self.conversation_history) >= 2:
                patient_message = self.conversation_history[-2]["content"].lower()
                reason_patterns = ["reason", "appointment for", "need to see", "problem", "issue", "symptom", "checkup"]
                if any(pattern in patient_message for pattern in reason_patterns):
                    # Extract the appointment reason
                    self.patient_info["appointment_reason"] = patient_message
                    self.state["got_appointment_reason"] = True
                    logger.info(f"Extracted appointment reason")
                    
            # Check if we have enough information to contact the hospital
            if (self.state["got_name"] and self.state["got_dob"] and 
                (self.state["got_insurance"] or self.state["got_appointment_reason"]) and
                not self.state["ready_for_hospital_call"]):
                self.state["ready_for_hospital_call"] = True
                logger.info("Patient has provided enough information for hospital call")
                
        except Exception as e:
            logger.error(f"Error in PatientAgent._update_state: {e}")
            # Don't let an error in state update break the whole flow


class HospitalAgent(ConversationAgent):
    """Agent for handling conversations with hospital receptionists."""
    
    def __init__(self, patient_info):
        """
        Initialize the HospitalAgent with the appropriate system prompt.
        
        Args:
            patient_info: Dictionary containing patient information
        """
        super().__init__(prompts.HOSPITAL_AGENT_PROMPT)
        self.patient_info = patient_info
        self.state = {
            "appointment_confirmed": False,
            "got_appointment_date": False,
            "got_appointment_time": False,
            "got_doctor_name": False
        }
        self.appointment_info = {
            "date": None,
            "time": None,
            "doctor": None,
            "special_instructions": None
        }
        self.conversation_counter = 0
    
    def generate_response(self, receptionist_message):
        """
        Generate a response to the receptionist's message.
        
        Args:
            receptionist_message: The receptionist's message
            
        Returns:
            str: The generated response
        """
        # Format the user message using the template
        user_message = prompts.HOSPITAL_AGENT_USER_TEMPLATE.format(
            name=self.patient_info.get("name", "Unknown"),
            dob=self.patient_info.get("dob", "Unknown"),
            insurance=self.patient_info.get("insurance", "Unknown"),
            reason=self.patient_info.get("appointment_reason", "medical appointment"),
            symptoms=self.patient_info.get("symptoms", "Unknown"),
            timeframe=self.patient_info.get("preferred_timeframe", "as soon as possible"),
            conversation_history=self.get_conversation_summary(),
            receptionist_message=receptionist_message
        )
        
        return super().generate_response(user_message)
    
    def _generate_mock_response(self, user_message):
        """
        Generate a mock response for the hospital agent.
        
        Args:
            user_message: The user's message
            
        Returns:
            str: A mock response
        """
        # Progress the conversation based on the number of exchanges
        self.conversation_counter += 1
        
        # Introduction
        if self.conversation_counter == 1:
            return f"Hello, this is Tofia calling from the automated appointment scheduling service. I'd like to schedule an appointment for {self.patient_info.get('name', 'a patient')}."
        
        # Provide patient information
        elif self.conversation_counter == 2:
            return f"The patient is experiencing {self.patient_info.get('symptoms', 'some symptoms')} and needs a {self.patient_info.get('appointment_reason', 'medical appointment')}. Their insurance is {self.patient_info.get('insurance', 'Unknown')}."
        
        # Respond to available slots
        elif self.conversation_counter == 3:
            self.state["got_appointment_date"] = True
            self.state["got_appointment_time"] = True
            self.appointment_info["date"] = "tomorrow"
            self.appointment_info["time"] = "2:30 PM"
            return "Tomorrow at 2:30 PM would work perfectly for the patient. Thank you."
        
        # Confirm details and doctor
        elif self.conversation_counter == 4:
            self.state["got_doctor_name"] = True
            self.appointment_info["doctor"] = "Dr. Smith"
            self.state["appointment_confirmed"] = True
            return "Great, I'll confirm the appointment with Dr. Smith tomorrow at 2:30 PM. I'll let the patient know. Thank you for your help."
        
        return "Thank you for your assistance with scheduling this appointment."
    
    def _update_state(self, response):
        """
        Update the state based on the current response.
        
        Args:
            response: The assistant's response
        """
        # In mock mode, state is updated by the _generate_mock_response method
        if hasattr(config, 'MOCK_MODE') and config.MOCK_MODE:
            return
            
        try:
            # Look for appointment date in conversation
            if not self.state["got_appointment_date"] and len(self.conversation_history) >= 2:
                patient_message = self.conversation_history[-2]["content"].lower()
                appointment_date_patterns = ["schedule", "appointment", "date"]
                if any(pattern in patient_message for pattern in appointment_date_patterns):
                    # This extracts dates in various formats
                    import re
                    # Match various date formats
                    date_patterns = [
                        r'\b\d{1,2}/\d{1,2}/\d{2,4}\b',  # MM/DD/YYYY or DD/MM/YYYY
                        r'\b\d{1,2}-\d{1,2}-\d{2,4}\b',   # MM-DD-YYYY or DD-MM-YYYY
                        r'\b(?:january|february|march|april|may|june|july|august|september|october|november|december|jan|feb|mar|apr|jun|jul|aug|sep|sept|oct|nov|dec)[.,\s]+\d{1,2}(?:st|nd|rd|th)?[.,\s]+\d{2,4}\b',  # Month DD, YYYY
                    ]
                    for pattern in date_patterns:
                        matches = re.findall(pattern, patient_message, re.IGNORECASE)
                        if matches:
                            self.appointment_info["date"] = matches[0]
                            self.state["got_appointment_date"] = True
                            logger.info(f"Extracted appointment date: {matches[0]}")
                            break
            
            # Look for appointment time
            if not self.state["got_appointment_time"] and len(self.conversation_history) >= 2:
                patient_message = self.conversation_history[-2]["content"].lower()
                appointment_time_patterns = ["at", "time"]
                if any(pattern in patient_message for pattern in appointment_time_patterns):
                    # Extract the time (simplified)
                    words = patient_message.split()
                    for idx, word in enumerate(words):
                        if any(pattern in word for pattern in appointment_time_patterns) and idx < len(words) - 1:
                            # Take words after the time keyword, up to 5 words
                            potential_time = " ".join(words[idx+1:idx+6]).rstrip(".,!?")
                            if potential_time:
                                self.appointment_info["time"] = potential_time
                                self.state["got_appointment_time"] = True
                                logger.info(f"Extracted appointment time: {potential_time}")
                                break
            
            # Look for doctor name
            if not self.state["got_doctor_name"] and len(self.conversation_history) >= 2:
                patient_message = self.conversation_history[-2]["content"].lower()
                doctor_name_patterns = ["doctor", "dr."]
                if any(pattern in patient_message for pattern in doctor_name_patterns):
                    # Extract doctor name (simplified)
                    words = patient_message.split()
                    for idx, word in enumerate(words):
                        if any(pattern in word for pattern in doctor_name_patterns) and idx < len(words) - 1:
                            # Take words after the doctor keyword, up to 5 words
                            potential_doctor = " ".join(words[idx+1:idx+6]).rstrip(".,!?")
                            if potential_doctor:
                                self.appointment_info["doctor"] = potential_doctor
                                self.state["got_doctor_name"] = True
                                logger.info(f"Extracted doctor name: {potential_doctor}")
                                break
            
            # Check if appointment is confirmed
            if (self.state["got_appointment_date"] and self.state["got_appointment_time"]):
                self.state["appointment_confirmed"] = True
                logger.info("Appointment confirmed")
                
        except Exception as e:
            logger.error(f"Error in HospitalAgent._update_state: {e}")
            # Don't let an error in state update break the whole flow
    
    def get_appointment_details(self):
        """
        Get the confirmed appointment details.
        
        Returns:
            dict: The appointment details if confirmed, None otherwise
        """
        if self.state["appointment_confirmed"]:
            return self.appointment_info
        return None
